<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>Schleupen.AS4.BusinessAdapter.UnitTests</AssemblyName>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="Certificates\Resources\client.pfx" />
        <None Update="appsettings.unittests.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <None Remove="Certificates\Resources\MP_AS4.pfx" />
        <None Remove="Certificates\Resources\MP_API.pfx" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="JunitXml.TestLogger" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\BusinessAdapter.MP.Console\BusinessAdapter.MP.Console.csproj" />
        <ProjectReference Include="..\BusinessAdapter.MP\BusinessAdapter.MP.csproj" />
        <ProjectReference Include="..\BusinessAdapter\BusinessAdapter.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Remove="Certificates\Resources\client_api_certificate.pfx" />
        <EmbeddedResource Include="Certificates\Resources\client_api_certificate.pfx" />
        <None Remove="Certificates\Resources\client_as4_certificate.pfx" />
        <EmbeddedResource Include="Certificates\Resources\client_as4_certificate.pfx" />
        <None Remove="Certificates\Resources\client_unspecific_certificate.pfx" />
        <EmbeddedResource Include="Certificates\Resources\client_unspecific_certificate.pfx" />
    </ItemGroup>
</Project>