#!/bin/bash
[[ -z "$1" ]] && { echo "Parameter 1 [used for Directory.Build.props filename] is empty" ; exit 1337; }
cd "$(dirname "$0")"
DIRECTORY_BUILD_PROPS_CFG_SWITCH_FILENAME=${1:-unkown}
DIRECTORY_BUILD_PROPS_CFG_FILENAME="Directory.Build.props"
DIRECTORY_BUILD_PROPS_BACKUP_FILENAME="Directory.Build.props.disabled"

echo "backup '${DIRECTORY_BUILD_PROPS_CFG_FILENAME}' to '${DIRECTORY_BUILD_PROPS_BACKUP_FILENAME}'"
mv ${DIRECTORY_BUILD_PROPS_CFG_FILENAME} ${DIRECTORY_BUILD_PROPS_BACKUP_FILENAME}
echo "rename '${DIRECTORY_BUILD_PROPS_CFG_SWITCH_FILENAME}' to '${DIRECTORY_BUILD_PROPS_CFG_FILENAME}'"
mv ${DIRECTORY_BUILD_PROPS_CFG_SWITCH_FILENAME} ${DIRECTORY_BUILD_PROPS_CFG_FILENAME}