param ($filename)

$DIRECTORY_BUILD_PROPS_CFG_SWITCH_FILENAME=($filename)
$DIRECTORY_BUILD_PROPS_CFG_FILENAME="Directory.Build.props"
$DIRECTORY_BUILD_PROPS_BACKUP_FILENAME="Directory.Build.props.disabled"

Write-Output "backup '$DIRECTORY_BUILD_PROPS_CFG_FILENAME' to '$DIRECTORY_BUILD_PROPS_BACKUP_FILENAME'"
Move-Item $DIRECTORY_BUILD_PROPS_CFG_FILENAME $DIRECTORY_BUILD_PROPS_BACKUP_FILENAME
Write-Output "rename '$DIRECTORY_BUILD_PROPS_CFG_SWITCH_FILENAME' to '$DIRECTORY_BUILD_PROPS_CFG_FILENAME'"
Move-Item $DIRECTORY_BUILD_PROPS_CFG_SWITCH_FILENAME $DIRECTORY_BUILD_PROPS_CFG_FILENAME